version: '3.9'

services: 
    db:
        image: postgres:9.4
        environment: 
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=guilh
        ports: 
            - "5432:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data
volumes: 
    postgres_data:
